apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-run-
spec:
  pipelineRef:
    name: build-deploy-canary
  params:
    - name: GIT_URL
      value: https://github.com/jkapl/ci-cd-istio-tekton 
    - name: BUILDER_IMAGE
      value: https://quay.io/buildah/stable:v1.14.8
    - name: REVISION
      value: master   
  workspaces:
    - name: build-deploy-workspace
      persistentVolumeClaim:
        claimName: workspace-pvc